services:
  wedding:
    depends_on:
      postgres:
        condition: service_healthy
    image: wedding:latest
    ports:
      - 3000:3000
    networks:
      - net
    environment:
      - NODE_ENV=production
      - DATABASE_URL=postgres://rendres:s3cr3t@postgres:5432/wedding
      - LOGTO_ENDPOINT=http://logto:3001
      - LOGTO_APP_ID=ew8dqhsw5s6r274i8g73y
      - LOGTO_APP_SECRET=39hNKEvuf30qUFIu7GkI6UiH0mzwwiEW
      - LOGTO_BASE_URL=http://wedding:3000

  postgres:
    image: postgres:17.1
    restart: always
    environment:
      POSTGRES_USER: rendres
      POSTGRES_PASSWORD: s3cr3t
    ports:
      - 5432:5432
    healthcheck:
      test: ["CMD", "pg_isready", "-U", "rendres", "-d", "wedding"]
      interval: 5s
      timeout: 5s
      retries: 5
    volumes:
      - postgres:/var/lib/postgresql/data
    networks:
      - net

  logto:
    depends_on:
      postgres:
        condition: service_healthy
    image: svhd/logto:1.22
    entrypoint: ["sh", "-c", "npm run cli db seed -- --swe && npm start"]
    ports:
      - 3001:3001
      - 3002:3002
    environment:
      - TRUST_PROXY_HEADER=1 # NOTE: enable when using traefik
      - DB_URL=postgres://rendres:s3cr3t@postgres:5432/logto
      # - ENDPOINT           # TODO: add when using custom domain
      # - ADMIN_ENDPOINT     # TODO: add when using custom domain
    networks:
      - net

networks:
  net:

volumes:
  postgres:
