# This action is used to generate a new release.
# Runs on pull requests and pushes to  the main branch.

name: Release Please

on:
  push:
    branches: main

permissions:
  contents: write
  pull-requests: write

jobs:
  release-please:
    runs-on: ubuntu-latest

    steps:
      - name: 🔀 Create a release PR
        uses: googleapis/release-please-action@v4
        with:
          token: ${{ secrets.GH_TOKEN }}
          release-type: node
